# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[nim]
disabled = true

[character]
success_symbol = "[λ](green)"
error_symbol = "[λ](red)"

[golang]
symbol = " "

[battery]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[elixir]
disabled = true

[kubernetes]
disabled = false
symbol = "⎈ "
style = "blue"
